import fs from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'
import * as jsx from 'react/jsx-runtime'
import {load,plain} from './helpers/foundation-harness.mjs'
const fixture=JSON.parse(fs.readFileSync('tests/fixtures/inbox-baseline.json','utf8')),directory='client/src/features/workspace/components/'
const icons=new Proxy({},{get:(_,name)=>props=>jsx.jsx(`icon:${String(name)}`,props)})
function render(name,props,side){const mocks={'react/jsx-runtime':jsx,'lucide-react':icons,'../../../shared/components/Avatar':{Avatar:props=>jsx.jsx('Avatar',props)}};mocks['./ChatRow']=load(directory+'ChatRow.tsx',mocks,{},fixture.files[directory+'ChatRow.tsx'][side]);const expand=node=>node==null||typeof node!=='object'?node:Array.isArray(node)?node.map(expand):typeof node.type==='function'?expand(node.type(node.props)):{type:node.type,key:node.key,props:Object.fromEntries(Object.entries(node.props).filter(([key])=>key!=='className').map(([key,value])=>[key,key==='children'?expand(value):typeof value==='function'?'CALLBACK':value]))};return plain(expand(load(directory+name+'.tsx',mocks,{},fixture.files[directory+name+'.tsx'][side])[name](props)))}
const chat={id:'unicode-id',kind:'direct',display_title:'Zoë محمد 東京 👩🏽‍💻'.repeat(8),preview:'📎 file.pdf · Voice message · مرحباً'.repeat(9),last_message_created_at:'2026-10-02T10:00:00Z'}
const callbacks=Object.fromEntries(['SelectChat','SelectCall','CallAgain','NewCall','SelectRequest','SelectFilter','ShowRequests','NewConversation','OpenSearch'].map(name=>['on'+name,()=>{}]))
test('ChatRow baseline equality covers selection, 0/1/9/99/100/string unread values, direct/group, empty/media/Unicode preview, image/fallback and 60/61-character drafts',()=>{let cases=0;for(const selected of [false,true])for(const kind of ['direct','group'])for(const unread_count of [0,1,9,99,100,'120',undefined])for(const draft of [undefined,'', 'x'.repeat(60),'x'.repeat(61),'مرحبا 👩🏽‍💻'.repeat(9)])for(const preview of ['',chat.preview]){const props={chat:{...chat,kind,unread_count,preview,peer_avatar_url:cases%2?'/fixture-avatar':null},selected,draft,onSelect(){}};assert.deepEqual(render('ChatRow',props,'after'),render('ChatRow',props,'before'));cases++}assert.equal(cases,280)})
test('Inbox baseline equality covers direct/group order, selected IDs, all/unread, requests/counts, error/offline, empty state and shared Calls history',()=>{for(const showCalls of [false,true])for(const filter of ['all','unread'])for(const showRequests of [false,true])for(const empty of [false,true])for(const online of [false,true]){const props={...callbacks,showCalls,filter,showRequests,online,userId:'me',activeChatId:chat.id,error:online?'':'Offline error',chats:empty?[]:[{...chat,unread_count:0},{...chat,id:'group',kind:'group',unread_count:100}],drafts:{group:'Draft'},requests:empty?[]:[{id:'req',display_name:'Taylor',username:'taylor'}],callHistory:empty?[]:[{id:'call',chat_id:'group',created_at:'2026-10-02T10:00:00Z',caller_id:'me',callee_id:'peer',call_type:'audio',status:'ended',other_name:'Taylor'}]};assert.deepEqual(render('InboxPane',props,'after'),render('InboxPane',props,'before'))}})
test('ChatRow native button forwards the original ID without modifying count or draft inputs',()=>{for(const side of ['before','after']){const calls=[],props={chat:{...chat,unread_count:100},selected:true,draft:'x'.repeat(61),onSelect:id=>calls.push(id)},mocks={'react/jsx-runtime':jsx,'lucide-react':icons,'../../../shared/components/Avatar':{Avatar:()=>null}},row=load(directory+'ChatRow.tsx',mocks,{},fixture.files[directory+'ChatRow.tsx'][side]).ChatRow(props);assert.equal(row.type,'button');assert.equal(row.props.type,'button');row.props.onClick();assert.deepEqual(calls,['unicode-id']);assert.equal(props.chat.unread_count,100);assert.equal(props.draft.length,61)}})
