import fs from 'node:fs'
import {restoreConversationVisual} from './helpers/conversation-visual-parity.mjs'
import test from 'node:test'
import assert from 'node:assert/strict'
import {execFileSync} from 'node:child_process'
import ts from 'typescript'
import postcss from 'postcss'
import {base,productionFiles,exclusive,excludeMigrated,inventory} from './helpers/inbox-audit.mjs'
import {buildProof} from './helpers/design-system-wiring-proof.mjs'
const fixture=JSON.parse(fs.readFileSync('tests/fixtures/inbox-baseline.json','utf8')),read=file=>restoreConversationVisual(file,fs.readFileSync(file,'utf8'))
function behavior(file,source){const tree=ts.createSourceFile(file,source,99,true,ts.ScriptKind.TSX),result=ts.transform(tree,[context=>{const visit=node=>ts.isJsxAttributes(node)?context.factory.updateJsxAttributes(node,node.properties.filter(n=>!ts.isJsxAttribute(n)||n.name.text!=='className')):ts.visitEachChild(node,visit,context);return node=>ts.visitNode(node,visit)}]);return ts.createPrinter().printFile(result.transformed[0])}
function rules(source,before=false){const rows=[];postcss.parse(source).walkRules(rule=>{const nesting=[];for(let p=rule.parent;p;p=p.parent)if(p.type==='atrule')nesting.unshift(`@${p.name} ${p.params}`);for(const selector of rule.selectors){if(before&&exclusive.test(selector))continue;if(!before&&(/Inbox presentation/.test(rule.prev()?.text??'')||/^\.inbox-(?:action|error|empty-action|content|chat-list|empty-copy)/.test(selector)||exclusive.test(selector)))continue;rows.push({selector:before?excludeMigrated(selector):selector,nesting,declarations:rule.nodes.filter(n=>n.type==='decl').map(n=>[n.prop,n.value,Boolean(n.important)])})}});return rows}
test('Inbox changes only JSX classes: every callback, ID, ARIA, role, value, condition, import and date/preview algorithm remains exact',()=>{assert.equal(fixture.base,base);for(const[file,record]of Object.entries(fixture.files)){assert.equal(record.before,execFileSync('git',['show',`${base}:${file}`],{encoding:'utf8'}));assert.equal(read(file),record.after);if(file.endsWith('.tsx'))assert.equal(behavior(file,record.before),behavior(file,record.after))}})
test('Inbox production scope freezes every other client/server/package/config file against the required main',()=>{const files=execFileSync('git',['ls-tree','-r','--name-only',base],{encoding:'utf8'}).trim().split('\n').filter(file=>file.startsWith('client/')||file.startsWith('server/')||['package.json','package-lock.json'].includes(file));for(const file of files)if(!productionFiles.includes(file))assert.equal(read(file),execFileSync('git',['show',`${base}:${file}`],{encoding:'utf8'}).replaceAll('\r\n','\n'),file);assert.deepEqual(execFileSync('git',['diff','--name-only',base,'--','client','server','package.json','package-lock.json'],{encoding:'utf8'}).trim().split('\n').sort(),[...new Set([...productionFiles,...Object.keys(JSON.parse(fs.readFileSync('tests/fixtures/conversation-visual-contract.json','utf8')).files),...Object.keys(JSON.parse(fs.readFileSync('tests/fixtures/composer-visual-contract.json','utf8')).files)])].sort())})
test('Unowned CSS declarations, nesting and cascade order stay exact; shared Calls/Requests empty contracts exclude only migrated Inbox instances',()=>{const file=productionFiles[2];assert.deepEqual(rules(read(file)),rules(fixture.files[file].before,true))})
test('Inbox owns semantic utilities without raw colors, arbitrary typography, transitions or obsolete green selectors',()=>{for(const file of productionFiles.slice(0,2)){assert.doesNotMatch(read(file),/#[\da-f]{3,8}\b|rgba?\(|hsla?\(|ui:(?:text|leading|tracking)-\[|ui:transition|ui:animate/)}assert.match(read(productionFiles[2]),/\.inbox-content, \.inbox-chat-list \{ min-height: 0; \}/);const css=postcss.parse(read(productionFiles[2]));css.walkRules(rule=>{if(exclusive.test(rule.selector)||/^\.inbox-(?:action|error|empty-action|content|chat-list|empty-copy)/.test(rule.selector)){for(const d of rule.nodes.filter(n=>n.type==='decl'))assert.doesNotMatch(d.value,/#|rgba?\(|hsla?\(/)}});assert.doesNotMatch(read(productionFiles[2]),/\.chat-list-item\.selected\s*\{|\.chat-row-copy (?:strong|small)\s*\{|\.search-box:hover\s*\{|\.group-label\s*\{/);assert.match(read(productionFiles[2]),/outline: 2px solid var\(--ds-color-focus\)/)})
test('Inbox source detection emits selected/hover/metadata utility contracts without changing global border properties',async()=>{const result=await buildProof('.git/visual07/utility-proof');for(const name of ['text-body-sm','text-label','text-caption','text-overline','bg-selected','border-l-brand','bg-brand-soft'])assert.ok(result.css.includes(name),name);assert.match(result.css,/var\(--ds-color-selected\)/);assert.match(result.css,/var\(--ds-color-brand\)/);assert.doesNotMatch(result.css,/@property --tw-border-style/)})
test('Inbox audit records current owner sites and reduction without changing an unrelated stylesheet',()=>{const file=productionFiles[2],before=inventory(fixture.files[file].before),after=inventory(read(file));assert.ok(after.length<before.length);assert.equal(read(file).split('\n').length<fixture.files[file].before.split('\n').length,true)})
