import fs from 'node:fs'
import {execFileSync} from 'node:child_process'
import postcss from 'postcss'
export const base='5e03916584781f7769243de88d4a9f785dbfe03f'
export const productionFiles=['client/src/features/workspace/components/InboxPane.tsx','client/src/features/workspace/components/ChatRow.tsx','client/src/shared/styles/platform.css']
export const exclusive=/\.(?:pane-heading|search-box|inbox-filters|request-count|chat-list-item|chat-row-copy|chat-row-meta|draft-label|has-draft|group-label|unread-pill|inbox-footnote)(?=[\s.:>#,\[]|$)/
// These contracts also belong to Calls/RequestsPanel. Exclude only migrated
// Inbox instances; the original declarations and their cascade order survive.
export const exclusions={'chat-list':'inbox-chat-list','list-section-label':'inbox-section-label','list-empty':'inbox-empty-state','empty-symbol':'inbox-empty-symbol','empty-title':'inbox-empty-title','empty-copy':'inbox-empty-copy','list-error':'inbox-error'}
export function excludeMigrated(selector){return selector.replace(/\.(chat-list|list-section-label|list-empty|empty-symbol|empty-title|empty-copy|list-error)(?=[\s.:>#,\[]|$)/g,(_,name)=>`.${name}:not(.${exclusions[name]})`)}
export function classification(selector){if(exclusive.test(selector))return /pane-heading|inbox-footnote/.test(selector)?'INBOX_SHELL':/search-box/.test(selector)?'SEARCH':/inbox-filters|request-count/.test(selector)?'ACTION':/selected|hover|draft/.test(selector)?'CHAT_ROW_STATE':'CHAT_ROW';if(/empty-|list-empty/.test(selector))return 'EMPTY_STATE';if(/chat-list|list-section-label|list-error/.test(selector))return 'LEGACY_COUPLING';if(/avatar|ui-/.test(selector))return 'SHARED_PRIMITIVE';return 'FEATURE_LOGIC'}
export function inventory(source){const rows=[];postcss.parse(source).walkRules(rule=>{const nesting=[];for(let p=rule.parent;p;p=p.parent)if(p.type==='atrule')nesting.unshift(`@${p.name} ${p.params}`);const selectors=rule.selectors.map(selector=>({selector,classification:classification(selector)}));if(selectors.some(s=>s.classification!=='FEATURE_LOGIC'))rows.push({line:rule.source.start.line,nesting,selectors,mixed:selectors.some(s=>s.classification==='FEATURE_LOGIC'),declarations:rule.nodes.filter(n=>n.type==='decl').map(n=>[n.prop,n.value,Boolean(n.important)])})});return rows}
if(process.argv.includes('--record')){const directory='docs/design-system/evidence-07';fs.mkdirSync(directory,{recursive:true});const files=Object.fromEntries(productionFiles.map(file=>[file,{before:execFileSync('git',['show',`${base}:${file}`],{encoding:'utf8'}),after:null}]));fs.writeFileSync('tests/fixtures/inbox-baseline.json',JSON.stringify({base,files},null,2)+'\n');fs.writeFileSync(directory+'/ownership-before.json',JSON.stringify({base,rules:inventory(files[productionFiles[2]].before),contracts:{loading:'No Inbox loading branch exists',search:'Native button opens SearchDialog; no Inbox input',typing:'No separate typing state',sending:'No separate sending/failure state',unread:'Positive Number(unread_count); render original value without cap',calls:'Header shared; history and empty state remain unchanged',requests:'Inline rows clearly Inbox-owned; RequestsPanel workflow excluded'}},null,2)+'\n')}
